from dataclasses import dataclass, field
from typing import List, Tuple, Optional, Union, Dict

# -----------------------------------------------------------------
# 1. THE "BLUEPRINT" (The dataclass)
# -----------------------------------------------------------------
@dataclass
class RoomDef:
    """
    Represents the 'blueprint' or 'encyclopedia entry' for a single room type.
    This is the static, unchanging data from the game's design.
    """
    
    # --- Core Properties (Almost every room has these) ---
    name: str 
    color: str 
    image_path: str # e.g., "assets/images/rooms/vault.png"
    
    # UPDATED: These can be a single number OR a (min, max) tuple
    rarity: Union[int, Tuple[int, int]]
    gem_cost: Union[int, Tuple[int, int]]
    
    doors: Tuple[bool, bool, bool, bool] # (Up, Right, Down, Left)

    # --- Optional Properties (Default to None or empty) ---
    placement_condition: Optional[str] = None # e.g., 'border_only'
    allowed_rows: Optional[Tuple[int, int]] = None # e.g., (3, 5)
    
    effect_id: Optional[str] = None
    
    # UPDATED: This can also be a single number or a (min, max) tuple
    effect_value: Optional[Union[int, Tuple[int, int]]] = None
    
    # UPDATED: This is now a dictionary
    # e.g., {"chest": (1, 2), "gem": (5, 10)}
    objects_in_room: Dict[str, Tuple[int, int]] = field(default_factory=dict)


# -----------------------------------------------------------------
# 2. THE "MASTER DATABASE" (The Catalogue)
# -----------------------------------------------------------------

ROOM_CATALOGUE: List[RoomDef] = [
    RoomDef(
        name="The Foundation",
        color="blue",
        image_path="images/the_foundation.png",
        rarity=3,
        gem_cost=0,
        doors=(False, True, True, True),
        placement_condition="not edges",
        allowed_rows=(1, 12),
        objects_in_room={'dig spots': (2, 5)},
    ),
    RoomDef(
        name="Entrance Hall",
        color="blue",
        image_path="images/entrance_hall.png",
        rarity=0,
        gem_cost=0,
        doors=(True, True, False, True),
        allowed_rows=(1, 12),
    ),
    RoomDef(
        name="Spare Room",
        color="blue",
        image_path="images/spare_room.png",
        rarity=0,
        gem_cost=0,
        doors=(True, False, True, False),
        allowed_rows=(1, 12),
        objects_in_room={'key': (1, 2), 'shovel': (1, 1)},
    ),
    RoomDef(
        name="Rotunda",
        color="blue",
        image_path="images/rotunda.png",
        rarity=3,
        gem_cost=3,
        doors=(False, False, True, True),
        allowed_rows=(1, 12),
    ),
    RoomDef(
        name="Parlor",
        color="blue",
        image_path="images/parlor.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, True),
        allowed_rows=(1, 12),
        objects_in_room={'apple': (0, 1), 'key': (1, 1), 'gem': (1, 1)},
    ),
    RoomDef(
        name="Billiard Room",
        color="blue",
        image_path="images/billiard_room.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, True),
        allowed_rows=(1, 12),
        objects_in_room={'key': (3, 3), 'banana': (0, 1), 'orange': (0, 1), 'gem': (1, 2), 'coin': (1, 11)},
    ),
    RoomDef(
        name="Gallery",
        color="blue",
        image_path="images/gallery.png",
        rarity=3,
        gem_cost=0,
        doors=(True, False, True, False),
        allowed_rows=(1, 12),
        objects_in_room={'gem': (1, 3), 'chest': (1, 1), 'paw': (1, 1), 'coin': (10, 10), 'key': (1, 1)},
    ),
    RoomDef(
        name="room 8",
        color="blue",
        image_path="images/room_8.png",
        rarity=3,
        gem_cost=0,
        doors=(False, False, True, True),
        allowed_rows=(1, 12),
        objects_in_room={'key': (1, 1)},
    ),
    RoomDef(
        name="Closet",
        color="blue",
        image_path="images/closet.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(1, 12),
        objects_in_room={'dice': (1, 1), 'gem': (0, 1), 'key': (0, 1), 'coin': (0, 20), 'shovel': (0, 1), 'banana': (1, 1)},
    ),
    RoomDef(
        name="Walk-in Closet",
        color="blue",
        image_path="images/walk-in_closet.png",
        rarity=1,
        gem_cost=1,
        doors=(False, False, True, False),
        allowed_rows=(1, 12),
        objects_in_room={'cupcake': (1, 1), 'dice': (2, 2), 'key': (1, 3), 'gem': (1, 2), 'coin': (0, 20), 'lockpick': (1, 1)},
    ),
    RoomDef(
        name="Attic",
        color="blue",
        image_path="images/attic.png",
        rarity=3,
        gem_cost=3,
        doors=(False, False, True, False),
        allowed_rows=(1, 12),
        objects_in_room={'key': (1, 4), 'gem': (1, 4), 'coin': (0, 20), 'lockpick': (1, 1), 'metaldetector': (1, 1), 'shovel': (1, 1)},
    ),
    RoomDef(
        name="Storeroom",
        color="blue",
        image_path="images/storeroom.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(1, 12),
        objects_in_room={'key': (1, 1), 'gem': (1, 1), 'coin': (1, 1), 'shovel': (1, 1)},
    ),
    RoomDef(
        name="Nook",
        color="blue",
        image_path="images/nook.png",
        rarity=1,
        gem_cost=0,
        doors=(False, True, True, False),
        allowed_rows=(13, 24),
        objects_in_room={'dice': (1, 1), 'chest': (1, 1)},
    ),
    RoomDef(
        name="Garage",
        color="blue",
        image_path="images/garage.png",
        rarity=2,
        gem_cost=1,
        doors=(False, False, True, False),
        placement_condition="Only draftable into or within the West Wing from North or West facing doors, on ranks 4 to 8.",
        allowed_rows=(13, 24),
        objects_in_room={'key': (3, 3), 'dig spot': (3, 3), 'shovel': (1, 1), 'lockpick': (1, 1)},
    ),
    RoomDef(
        name="Music Room",
        color="blue",
        image_path="images/music_room.png",
        rarity=2,
        gem_cost=2,
        doors=(False, False, True, True),
        allowed_rows=(13, 24),
        effect_id="key",
        effect_value=1,
        objects_in_room={'chest': (1, 1), 'key': (2, 2)},
    ),
    RoomDef(
        name="Locker Room",
        color="blue",
        image_path="images/locker_room.png",
        rarity=3,
        gem_cost=1,
        doors=(True, False, True, False),
        allowed_rows=(13, 24),
        effect_id="apple",
        effect_value=1,
        objects_in_room={'key': (1, 4)},
    ),
    RoomDef(
        name="Den",
        color="blue",
        image_path="images/den.png",
        rarity=0,
        gem_cost=0,
        doors=(True, True, False, True),
        allowed_rows=(13, 24),
        objects_in_room={'dice': (2, 2), 'paw': (0, 1)},
    ),
    RoomDef(
        name="Wine Cellar",
        color="blue",
        image_path="images/wine_cellar.png",
        rarity=3,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(13, 24),
        objects_in_room={'gem': (3, 3), 'dice': (0, 2), 'key': (0, 1), 'coin': (0, 3), 'lockpick': (0, 1), 'shovel': (0, 1)},
    ),
    RoomDef(
        name="Trophy Room",
        color="blue",
        image_path="images/trophy_room.png",
        rarity=3,
        gem_cost=5,
        doors=(False, False, True, True),
        allowed_rows=(13, 24),
        objects_in_room={'ge': (8, 8), 'dice': (0, 1), 'shovel': (0, 1)},
    ),
    RoomDef(
        name="Ballroom",
        color="blue",
        image_path="images/ballroom.png",
        rarity=2,
        gem_cost=2,
        doors=(True, False, True, False),
        allowed_rows=(13, 24),
        effect_id="add_gem",
        effect_value=2,
        objects_in_room={'orange': (0, 1), 'key': (0, 1), 'coin': (0, 8), 'paw': (1, 1)},
    ),
    RoomDef(
        name="Pantry",
        color="blue",
        image_path="images/pantry.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, True),
        allowed_rows=(13, 24),
        effect_id="add_coin",
        effect_value=4,
        objects_in_room={'apple': (1, 3), 'banana': (1, 2), 'orange': (0, 1)},
    ),
    RoomDef(
        name="Office",
        color="blue",
        image_path="images/office.png",
        rarity=1,
        gem_cost=2,
        doors=(False, False, True, True),
        allowed_rows=(13, 24),
        objects_in_room={'apple': (0, 1), 'dice': (0, 2), 'coin': (0, 12), 'key': (0, 1)},
    ),
    RoomDef(
        name="Rumpus Room",
        color="blue",
        image_path="images/rumpus_room.png",
        rarity=1,
        gem_cost=1,
        doors=(True, False, True, False),
        allowed_rows=(13, 24),
        objects_in_room={'banana': (1, 1), 'dice': (0, 2), 'lockpick': (0, 1), 'paw': (0, 1), 'key': (0, 1)},
    ),
    RoomDef(
        name="Vault",
        color="blue",
        image_path="images/vault.png",
        rarity=3,
        gem_cost=3,
        doors=(False, False, True, False),
        allowed_rows=(13, 24),
        effect_id="add_coin",
        effect_value=40,
        objects_in_room={'gem': (1, 3), 'key1': (0, 1), 'key': (0, 1)},
    ),
    RoomDef(
        name="Drawing Room",
        color="blue",
        image_path="images/drawing_room.png",
        rarity=0,
        gem_cost=1,
        doors=(False, True, True, True),
        allowed_rows=(25, 36),
        objects_in_room={'apple': (1, 2), 'banana': (0, 1), 'coin': (0, 20)},
    ),
    RoomDef(
        name="Study",
        color="blue",
        image_path="images/study.png",
        rarity=2,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(25, 36),
        effect_id="add_gem",
        effect_value=3,
        objects_in_room={'apple': (1, 2), 'key': (0, 1), 'dice': (0, 2), 'coin': (0, 5), 'lockpick': (0, 1)},
    ),
    RoomDef(
        name="Library",
        color="blue",
        image_path="images/library.png",
        rarity=2,
        gem_cost=0,
        doors=(False, False, True, True),
        allowed_rows=(25, 36),
        objects_in_room={'apple': (0, 1), 'key': (0, 1)},
    ),
    RoomDef(
        name="Chamber of Mirrors",
        color="blue",
        image_path="images/chamber_of_mirrors.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(25, 36),
        objects_in_room={'orange': (0, 4), 'key': (0, 4), 'coin': (0, 4), 'gem': (0, 4)},
    ),
    RoomDef(
        name="The Pool",
        color="blue",
        image_path="images/the_pool.png",
        rarity=1,
        gem_cost=1,
        doors=(False, True, True, True),
        allowed_rows=(25, 36),
        objects_in_room={'banana': (0, 1), 'key': (1, 3)},
    ),
    RoomDef(
        name="Workshop",
        color="blue",
        image_path="images/workshop.png",
        rarity=2,
        gem_cost=0,
        doors=(True, False, True, False),
        allowed_rows=(25, 36),
        objects_in_room={'coin': (0, 20), 'lockpick': (0, 1), 'paw': (0, 1), 'metaldetector': (0, 1), 'shovel': (0, 1)},
    ),
    RoomDef(
        name="Drafting Studio",
        color="blue",
        image_path="images/drafting_studio.png",
        rarity=3,
        gem_cost=2,
        doors=(True, False, True, False),
        allowed_rows=(25, 36),
        objects_in_room={'apple': (2, 2), 'key': (1, 1), 'coin': (0, 10)},
    ),
    RoomDef(
        name="Utility Closet",
        color="blue",
        image_path="images/utility_closet.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(25, 36),
        objects_in_room={'shovel': (0, 1), 'coin': (0, 10), 'lockpick': (0, 1)},        
    ),
    RoomDef(
        name="Boiler Room",
        color="blue",
        image_path="images/boiler_room.png",
        rarity=2,
        gem_cost=1,
        doors=(False, True, True, True),
        allowed_rows=(25, 36),
        effect_id="metaldetector",
        effect_value=1,
        objects_in_room={'shovel': (1, 1)},
    ),
    RoomDef(
        name="Pump Room",
        color="blue",
        image_path="images/pump_room.png",
        rarity=2,
        gem_cost=0,
        doors=(False, False, True, True),
        allowed_rows=(25, 36),
        objects_in_room={'key': (1, 1), 'gem': (1, 1)},
    ),
    RoomDef(
        name="Security",
        color="blue",
        image_path="images/security.png",
        rarity=1,
        gem_cost=1,
        doors=(False, True, True, True),
        placement_condition="apple",
        allowed_rows=(25, 36),
        effect_id="0,2",
        effect_value=(0, 1),
        objects_in_room={'orange': (0, 1), 'coin': (0, 7), 'gem': (0, 2), 'lockpick': (0, 1)},
    ),
    RoomDef(
        name="Laboratory",
        color="blue",
        image_path="images/laboratory.png",
        rarity=1,
        gem_cost=1,
        doors=(False, False, True, True),
        placement_condition="apple",
        allowed_rows=(25, 36),
        effect_id="1",
        effect_value=1,
    ),
    RoomDef(
        name="Sauna",
        color="blue",
        image_path="images/sauna.png",
        rarity=2,
        gem_cost=0,
        doors=(False, False, True, False),
        placement_condition="pool",
        allowed_rows=(37, 45),
        effect_id="add_step",
        effect_value=20,
        objects_in_room={'key': (1, 1), 'gem': (1, 4), 'coin': (0, 3)},
    ),
    RoomDef(
        name="Coat Check",
        color="blue",
        image_path="images/coat_check.png",
        rarity=1,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(37, 45),
        effect_id="add_key",
        effect_value=1,
        objects_in_room={'cupcake': (0, 1), 'gem': (0, 2), 'coin': (5, 5)},
    ),
    RoomDef(
        name="Mail Room",
        color="blue",
        image_path="images/mail_room.png",
        rarity=0,
        gem_cost=2,
        doors=(False, False, True, False),
        allowed_rows=(37, 45),
        effect_id="add_step",
        effect_value=(0, 10),
        objects_in_room={'dice': (0, 2), 'key': (1, 2), 'gem': (1, 2), 'lockpick': (0, 1), 'coin': (0, 20)},
    ),
    RoomDef(
        name="Freezer",
        color="blue",
        image_path="images/freezer.png",
        rarity=3,
        gem_cost=0,
        doors=(False, False, True, False),
        allowed_rows=(37, 45),
        objects_in_room={'gem': (1, 2), 'key': (1, 1)},
    ),
    RoomDef(
        name="Dining Room",
        color="blue",
        image_path="images/dining_room.png",
        rarity=1,
        gem_cost=0,
        doors=(False, True, True, True),
        allowed_rows=(37, 45),
        effect_id="add_step",
        effect_value=40,
        objects_in_room={'key': (0, 1), 'gem': (1, 2), 'coin': (0, 20)},
    ),
    RoomDef(
        name="Observatory",
        color="blue",
        image_path="images/observatory.png",
        rarity=1,
        gem_cost=1,
        doors=(False, False, True, True),
        allowed_rows=(37, 45),
        objects_in_room={'dice': (1, 1), 'chest': (1, 1)},
    ),
    RoomDef(
        name="Conference Room",
        color="blue",
        image_path="images/conference_room.png",
        rarity=2,
        gem_cost=0,
        doors=(False, True, True, True),
        placement_condition="apple",
        allowed_rows=(37, 45),
        effect_id="1",
        effect_value=(0, 1),
        objects_in_room={'orange': (0, 1), 'key': (0, 1)},
    ),
    RoomDef(
        name="Aquarium",
        color="blue",
        image_path="images/aquarium.png",
        rarity=2,
        gem_cost=1,
        doors=(False, True, True, True),
        allowed_rows=(37, 45),
        objects_in_room={'key': (2, 2), 'gem': (1, 1), 'shovel': (1, 1)},
    ),
    RoomDef(
        name="Antechamber",
        color="blue",
        image_path="images/antechamber.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, False),
        placement_condition="9,3",
        allowed_rows=(37, 45),
    ),
    RoomDef(
        name="Bedroom",
        color="purple",
        image_path="images/bedroom.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, True),
        effect_id="add_step",
        effect_value=2,
        objects_in_room={'apple': (0, 1), 'dice': (1, 1), 'key': (1, 1), 'gem': (1, 1), 'coin': (3, 3)},
    ),
    RoomDef(
        name="Boudoir",
        color="purple",
        image_path="images/boudoir.png",
        rarity=1,
        gem_cost=0,
        doors=(False, False, True, True),
        effect_id="add_gem",
        effect_value=1,
        objects_in_room={'key': (2, 2), 'gem': (1, 1), 'coin': (5, 5), 'Guest Bedroom': (0, 0)},
    ),
    RoomDef(
        name="Guest Bedroom",
        color="purple",
        image_path="images/guest_bedroom.png",
        rarity=0,
        gem_cost=0,
        doors=(False, False, True, False),
        effect_id="add_step",
        effect_value=10,
        objects_in_room={'key': (1, 1), 'gem': (1, 1)},
    ),
    RoomDef(
        name="Nursery",
        color="purple",
        image_path="images/nursery.png",
        rarity=0,
        gem_cost=1,
        doors=(False, False, True, False),
        effect_id="add_step",
        effect_value=5,
        objects_in_room={'dice': (2, 2), 'key': (1, 1), 'gem': (1, 1), 'coin': (3, 3), 'paw': (1, 1)},
    ),
    RoomDef(
        name="Servant's Quarters",
        color="purple",
        image_path="images/servant's_quarters.png",
        rarity=2,
        gem_cost=1,
        doors=(False, False, True, False),
        effect_id="add_key",
        effect_value=1,
        objects_in_room={'dice': (2, 2), 'gem': (1, 1), 'metaldetector': (1, 1), 'shovel 1': (1, 1)},
    ),
    RoomDef(
        name="Bunk Room",
        color="purple",
        image_path="images/bunk_room.png",
        rarity=2,
        gem_cost=0,
        doors=(False, False, True, False),
        objects_in_room={'banana': (2, 2), 'keys': (2, 2), 'gem': (2, 2), 'coin': (4, 4)},
    ),
    RoomDef(
        name="Her Ladyship's Chamber",
        color="purple",
        image_path="images/her_ladyship's_chamber.png",
        rarity=3,
        gem_cost=0,
        doors=(False, False, True, False),
        effect_id="add_step",
        effect_value=10,
        objects_in_room={'banana': (1, 1), 'key': (1, 1), 'gem': (1, 1), 'coin': (0, 20), 'cupcake': (1, 1)},
    ),
    RoomDef(
        name="Master Bedroom",
        color="purple",
        image_path="images/master_bedroom.png",
        rarity=3,
        gem_cost=2,
        doors=(False, False, True, False),
        placement_condition="dice",
        effect_id="2",
        effect_value=(0, 9),
        objects_in_room={'gem': (1, 3), 'lockpick': (0, 1)},
    ),
]
